apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jdbc-demo
type: Opaque
stringData:
  POSTGRES_DB:       jdbc_demo
  POSTGRES_USER:     jdbc_user
  POSTGRES_PASSWORD: jdbc_pass

